baseURL: https://d-sch.github.io
languageCode: en-us
title: d-sch pages
theme: dsch

buildDrafts: false

module:
  mounts:
    - source: content
      target: content
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.js
      target: assets/js/bootstrap.bundle.js

_merge: shallow
markup:
  goldmark:
    parser:
      attribute:
        block: true

menu:
  main:
    - name: Home
      pageRef: /
      weight: 110

    - name: News
      pageRef: /news
      weight: 120

    - name: Blog
      pageRef: /posts
      weight: 130

    - name: Tags
      pageRef: /tags
      weight: 140
  footer:
    - name: About
      pageRef: /footer/about
      weight: 120
    - name: Legal
      pageRef: /footer/legal
      weight: 120
    - name: Privacy
      pageRef: /footer/privacy
      weight: 120